### ISSUE TITLE
Remover referências e ajustar o author

### ISSUE THREAD

**Issue by willianjusten** [igoroctaviano/igoroctaviano.github.io#3]
Cara, vou te ser bem sincero, há algum tempo fico curioso no meu github, apontar como se eu tivesse feito coisa para caralho no seu blog...

Hoje eu fui ver e pow...você fez uma coisa MUITO MUITO MUITO errada... Você clonou meu repositório ao invés de forkar e subiu no seu github como se fosse um repositório do zero. 

Sabe qual o problema disso? É que eu estou como contribuinte da maioria dos seus posts, o que não é a realidade....

Você poderia por favor, remover minhas referências e botar você como o autor? Usar meu template não é o problema, o ruim é estar ligado como se eu tivesse contribuido, isso afeta até meu histórico de commits...

Para fazer isso, basta seguir esses [passos aqui](https://help.github.com/articles/changing-author-info/)

**Comment by willianjusten** [comment]
Peço por favor que corrija isso, pois é bastante prejudicial para minhas métricas. Afinal de contas, o seu blog será sempre o que eu mais contribui, afinal de contas tem quase 600 commits só meus...

**Comment by igoroctaviano** [comment]
Willian,

"Puts", que trabalho que estou de dando em velho...
Peço mil desculpas, sei que você foi obrigado a me alertar dessas coisas,
realmente eu estava procurando um blog pra brincar com jekyll e git na
facul e acabou
nessa barberagem colossal.

Fiz os procedimento que você me informou, caso ocorrer mais alguma coisa eu
realmente precisarei dropar (com dor no coração, porque o template ficou
foda) o blog por enquanto, montar um do zero pra aprender primeiro.

*Cara, ingenuidade a minha em sair utilizando o material assinado sem saber
o básico
de todas as ferramentas constituintes, não foi atoa que você deixou um blog
blank
pra pessoas usarem, acho que era um template antigo, então usei o teu (azar
pra você, teimosia pra mim).

Agradeço novamente, pela paciência de Buddha.


*--*

*Atenciosamente,*



*Igor Octaviano Ribeiro Rezende*


Skype: igoroctaviano

**Comment by willianjusten** [comment]
Relaxa, você não precisa dropar o template não, suas modificações ficaram legais e ele é seu.

Eu vi aqui e ainda não funcionou corretamente (sabe-se lá pq...)

Minha dica:

Apaga o repositório do git, cria um novo, com mesmo nome e aí sim dá push do código. Ele vai subir como se nada tivesse acontecido, mas como uma nova referência. Creio que isso será suficiente para corrigir.

**Comment by willianjusten** [comment]
Desculpa se fui ignorante e falei algo que possa ter lhe magoado, é que só fiquei bolado com meu github todo estranho nas contribuições e eu uso muito ele como minha ferramenta de trabalho.

**Comment by igoroctaviano** [comment]
Na verdade é que eu estou tipo: "que bagunça foi essa que eu fiz, e perai.. ainda continuo fazendo"? eu quem lhe devo desculpas meu caro! pois meu git tem todo o direito de estar estrado, o seu não hehe.
